### ISSUE TITLE
JWT/Passport and Vuex (feature request)

### ISSUE THREAD

**Issue by mandofever78** [impxd/laravel-quasar-pwa-template#2]
Would you have any interest in adding JWT/Oauth--Laravel Passport authorization as well as Vuex to the mix here, or be open to pull requests to that effect?

**Comment by impxd** [comment]
Well, I think that depends by the requirements of each project. Laravel and Quasar (with Vue) do not mark you a workflow. Remember that this is just a template, you need to extend it.

I certainly use Vuex, but not Laravel Passport , axios nor jquery.
If you want to use them just install them by a `npm` or `composer install` command, and modify your **main.js**

In order to register the Passport Vue components, that would be like:
```
Vue.component(
    'passport-clients',
    require('./../resources/assets/js/components/passport/Clients.vue')
);
```
I guess. And add `/oauth` to the proxy table.
You would need to read their docs.
Good luck.
